sudo: false
language: ruby
rvm:
  - 2.2.0
cache: bundler
bundler_args: --without test --jobs 3 --retry 3
script: "cd guides && bundle exec rake guides:generate:html:ko:publish ALL=1"
branches:
  only:
    - guides-ko
